/** football-data.org team ID → { en, ru } */
export const COACHES_BY_TEAM_ID: Record<number, { en: string; ru: string }> = {
  758:  { en: 'Marcelo Bielsa',        ru: 'Марсело Бьелса' },
  759:  { en: 'Julian Nagelsmann',     ru: 'Юлиан Нагельсманн' },
  760:  { en: 'Luis de la Fuente',     ru: 'Луис де ла Фуэнте' },
  761:  { en: 'Gustavo Alfaro',        ru: 'Густаво Альфаро' },
  762:  { en: 'Lionel Scaloni',        ru: 'Лионель Скалони' },
  763:  { en: 'Otto Addo',             ru: 'Отто Аддо' },
  764:  { en: 'Dorival Júnior',        ru: 'Дорвал Жуниор' },
  765:  { en: 'Roberto Martínez',      ru: 'Роберто Мартинес' },
  766:  { en: 'Hajime Moriyasu',       ru: 'Хадзиме Морияс' },
  769:  { en: 'Javier Aguirre',        ru: 'Хавьер Агирре' },
  770:  { en: 'Thomas Tuchel',         ru: 'Томас Тухель' },
  771:  { en: 'Mauricio Pochettino',   ru: 'Маурисио Почеттино' },
  772:  { en: 'Hong Myung-bo',         ru: 'Хон Мён Бо' },
  773:  { en: 'Didier Deschamps',      ru: 'Дидье Дешам' },
  774:  { en: 'Hugo Broos',            ru: 'Юго Брус' },
  778:  { en: 'Nabil Neghiz',          ru: 'Набиль Негиз' },
  779:  { en: 'Tony Popovic',          ru: 'Тони Попович' },
  783:  { en: 'Darren Bazeley',        ru: 'Даррен Бейзли' },
  788:  { en: 'Murat Yakin',           ru: 'Мурат Якин' },
  791:  { en: 'Sébastien Beccacece',   ru: 'Себастьян Беккасесе' },
  792:  { en: 'Jon Dahl Tomasson',     ru: 'Йон Даль Томассон' },
  798:  { en: 'Ivan Hašek',            ru: 'Иван Хашек' },
  799:  { en: 'Zlatko Dalić',          ru: 'Златко Далич' },
  801:  { en: 'Stefano Pioli',         ru: 'Стефано Пиоли' },
  802:  { en: 'Jalel Kadri',           ru: 'Жалель Кадри' },
  803:  { en: 'Vincenzo Montella',     ru: 'Винченцо Монтелла' },
  804:  { en: 'Aliou Cissé',           ru: 'Алиу Сиссе' },
  805:  { en: 'Domenico Tedesco',      ru: 'Доменико Тедеско' },
  815:  { en: 'Walid Regragui',        ru: 'Валид Реграги' },
  816:  { en: 'Ralf Rangnick',         ru: 'Ральф Рангник' },
  818:  { en: 'Néstor Lorenzo',        ru: 'Нестор Лоренсо' },
  825:  { en: 'Emad El-Nakhlawy',      ru: 'Эмад Эль-Нахлауи' },
  828:  { en: 'Jesse Marsch',          ru: 'Джесси Марш' },
  836:  { en: 'Marc Collat',           ru: 'Марк Коллат' },
  840:  { en: 'Amir Ghalenoei',        ru: 'Амир Галенои' },
  1060: { en: 'Sergej Barbarez',       ru: 'Сергей Барбарез' },
  1836: { en: 'Thomas Christiansen',   ru: 'Томас Кристиансен' },
  1930: { en: 'Bubista',               ru: 'Бубиста' },
  1934: { en: 'Sébastien Desabre',     ru: 'Себастьян Дезабр' },
  1935: { en: 'Emerse Faé',            ru: 'Эмерс Фаэ' },
  8030: { en: 'Carlos Queiroz',        ru: 'Карлос Кейрос' },
  8049: { en: 'Hussein Ammouta',       ru: 'Хусейн Аммута' },
  8062: { en: 'Jesús Casas',           ru: 'Хесус Касас' },
  8070: { en: 'Srecko Katanec',        ru: 'Срецко Катанец' },
  8601: { en: 'Ronald Koeman',         ru: 'Рональд Куман' },
  8872: { en: 'Ståle Solbakken',       ru: 'Столе Солбаккен' },
  8873: { en: 'Steve Clarke',          ru: 'Стив Кларк' },
  9460: { en: 'Remko Bicentini',       ru: 'Ремко Бисентини' },
};

/** Fallback lookup by English team name */
const COACHES_BY_NAME: Record<string, { en: string; ru: string } | undefined> = {
  'Uruguay':            COACHES_BY_TEAM_ID[758],
  'Germany':            COACHES_BY_TEAM_ID[759],
  'Spain':              COACHES_BY_TEAM_ID[760],
  'Paraguay':           COACHES_BY_TEAM_ID[761],
  'Argentina':          COACHES_BY_TEAM_ID[762],
  'Ghana':              COACHES_BY_TEAM_ID[763],
  'Brazil':             COACHES_BY_TEAM_ID[764],
  'Portugal':           COACHES_BY_TEAM_ID[765],
  'Japan':              COACHES_BY_TEAM_ID[766],
  'Mexico':             COACHES_BY_TEAM_ID[769],
  'England':            COACHES_BY_TEAM_ID[770],
  'United States':      COACHES_BY_TEAM_ID[771],
  'South Korea':        COACHES_BY_TEAM_ID[772],
  'France':             COACHES_BY_TEAM_ID[773],
  'South Africa':       COACHES_BY_TEAM_ID[774],
  'Algeria':            COACHES_BY_TEAM_ID[778],
  'Australia':          COACHES_BY_TEAM_ID[779],
  'New Zealand':        COACHES_BY_TEAM_ID[783],
  'Switzerland':        COACHES_BY_TEAM_ID[788],
  'Ecuador':            COACHES_BY_TEAM_ID[791],
  'Sweden':             COACHES_BY_TEAM_ID[792],
  'Czechia':            COACHES_BY_TEAM_ID[798],
  'Croatia':            COACHES_BY_TEAM_ID[799],
  'Saudi Arabia':       COACHES_BY_TEAM_ID[801],
  'Tunisia':            COACHES_BY_TEAM_ID[802],
  'Turkey':             COACHES_BY_TEAM_ID[803],
  'Senegal':            COACHES_BY_TEAM_ID[804],
  'Belgium':            COACHES_BY_TEAM_ID[805],
  'Morocco':            COACHES_BY_TEAM_ID[815],
  'Austria':            COACHES_BY_TEAM_ID[816],
  'Colombia':           COACHES_BY_TEAM_ID[818],
  'Egypt':              COACHES_BY_TEAM_ID[825],
  'Canada':             COACHES_BY_TEAM_ID[828],
  'Haiti':              COACHES_BY_TEAM_ID[836],
  'Iran':               COACHES_BY_TEAM_ID[840],
  'Bosnia-Herzegovina': COACHES_BY_TEAM_ID[1060],
  'Panama':             COACHES_BY_TEAM_ID[1836],
  'Cape Verde Islands': COACHES_BY_TEAM_ID[1930],
  'Cape Verde':         COACHES_BY_TEAM_ID[1930],
  'Congo DR':           COACHES_BY_TEAM_ID[1934],
  'Ivory Coast':        COACHES_BY_TEAM_ID[1935],
  'Qatar':              COACHES_BY_TEAM_ID[8030],
  'Jordan':             COACHES_BY_TEAM_ID[8049],
  'Iraq':               COACHES_BY_TEAM_ID[8062],
  'Uzbekistan':         COACHES_BY_TEAM_ID[8070],
  'Netherlands':        COACHES_BY_TEAM_ID[8601],
  'Norway':             COACHES_BY_TEAM_ID[8872],
  'Scotland':           COACHES_BY_TEAM_ID[8873],
  'Curaçao':            COACHES_BY_TEAM_ID[9460],
};

export function getCoach(
  teamNameEn: string,
  teamId: number | undefined,
  apiCoach: { name: string } | null,
  locale: string,
): string | null {
  // API coach takes priority
  if (apiCoach?.name) {
    const entry = teamId ? COACHES_BY_TEAM_ID[teamId] : COACHES_BY_NAME[teamNameEn];
    if (locale === 'ru' && entry) return entry.ru;
    return apiCoach.name;
  }

  // Fallback from static map
  const entry = (teamId ? COACHES_BY_TEAM_ID[teamId] : null) ?? COACHES_BY_NAME[teamNameEn];
  if (!entry) return null;
  return locale === 'ru' ? entry.ru : entry.en;
}
