/** English → [full RU name, short RU name] */
export const TEAM_NAMES_RU: Record<string, [string, string]> = {
  // ЧМ 2026
  'Algeria':             ['Алжир',              'Алжир'],
  'Argentina':           ['Аргентина',          'Аргентина'],
  'Australia':           ['Австралия',          'Австралия'],
  'Austria':             ['Австрия',            'Австрия'],
  'Belgium':             ['Бельгия',            'Бельгия'],
  'Bosnia-Herzegovina':  ['Босния и Герц.',     'Босния'],
  'Brazil':              ['Бразилия',           'Бразилия'],
  'Canada':              ['Канада',             'Канада'],
  'Cape Verde Islands':  ['Кабо-Верде',         'Кабо-Верде'],
  'Cape Verde':          ['Кабо-Верде',         'Кабо-Верде'],
  'Colombia':            ['Колумбия',           'Колумбия'],
  'Congo DR':            ['ДР Конго',           'Конго ДР'],
  'Croatia':             ['Хорватия',           'Хорватия'],
  'Curaçao':             ['Кюрасао',            'Кюрасао'],
  'Czechia':             ['Чехия',              'Чехия'],
  'Czech Republic':      ['Чехия',              'Чехия'],
  'Ecuador':             ['Эквадор',            'Эквадор'],
  'Egypt':               ['Египет',             'Египет'],
  'England':             ['Англия',             'Англия'],
  'France':              ['Франция',            'Франция'],
  'Germany':             ['Германия',           'Германия'],
  'Ghana':               ['Гана',               'Гана'],
  'Haiti':               ['Гаити',              'Гаити'],
  'Iran':                ['Иран',               'Иран'],
  'Iraq':                ['Ирак',               'Ирак'],
  'Ivory Coast':         ['Кот-д\'Ивуар',       'К. д\'Ивуар'],
  'Japan':               ['Япония',             'Япония'],
  'Jordan':              ['Иордания',           'Иордания'],
  'Mexico':              ['Мексика',            'Мексика'],
  'Morocco':             ['Марокко',            'Марокко'],
  'Netherlands':         ['Нидерланды',         'Нидерланды'],
  'New Zealand':         ['Новая Зеландия',     'Н. Зеландия'],
  'Norway':              ['Норвегия',           'Норвегия'],
  'Panama':              ['Панама',             'Панама'],
  'Paraguay':            ['Парагвай',           'Парагвай'],
  'Poland':              ['Польша',             'Польша'],
  'Portugal':            ['Португалия',         'Португалия'],
  'Qatar':               ['Катар',              'Катар'],
  'Saudi Arabia':        ['Саудовская Аравия',  'Саудовская'],
  'Scotland':            ['Шотландия',          'Шотландия'],
  'Senegal':             ['Сенегал',            'Сенегал'],
  'Serbia':              ['Сербия',             'Сербия'],
  'South Africa':        ['ЮАР',                'ЮАР'],
  'South Korea':         ['Южная Корея',        'Ю. Корея'],
  'Korea Republic':      ['Южная Корея',        'Ю. Корея'],
  'Spain':               ['Испания',            'Испания'],
  'Sweden':              ['Швеция',             'Швеция'],
  'Switzerland':         ['Швейцария',          'Швейцария'],
  'Tunisia':             ['Тунис',              'Тунис'],
  'Turkey':              ['Турция',             'Турция'],
  'United States':       ['США',                'США'],
  'USA':                 ['США',                'США'],
  'Uruguay':             ['Уругвай',            'Уругвай'],
  'Uzbekistan':          ['Узбекистан',         'Узбекистан'],
  // Частые сборные вне ЧМ
  'Italy':               ['Италия',             'Италия'],
  'Wales':               ['Уэльс',              'Уэльс'],
  'Denmark':             ['Дания',              'Дания'],
  'Hungary':             ['Венгрия',            'Венгрия'],
  'Romania':             ['Румыния',            'Румыния'],
  'Ukraine':             ['Украина',            'Украина'],
  'Russia':              ['Россия',             'Россия'],
  'Greece':              ['Греция',             'Греция'],
  'Ireland':             ['Ирландия',           'Ирландия'],
  'Slovakia':            ['Словакия',           'Словакия'],
  'Slovenia':            ['Словения',           'Словения'],
  'Finland':             ['Финляндия',          'Финляндия'],
  'Iceland':             ['Исландия',           'Исландия'],
  'Israel':              ['Израиль',            'Израиль'],
  'Albania':             ['Албания',            'Албания'],
  'North Macedonia':     ['Северная Македония', 'С. Македония'],
  'Kosovo':              ['Косово',             'Косово'],
  'Georgia':             ['Грузия',             'Грузия'],
  'Azerbaijan':          ['Азербайджан',        'Азербайджан'],
  'Kazakhstan':          ['Казахстан',          'Казахстан'],
  'China':               ['Китай',              'Китай'],
  'Indonesia':           ['Индонезия',          'Индонезия'],
  'Thailand':            ['Таиланд',            'Таиланд'],
  'Vietnam':             ['Вьетнам',            'Вьетнам'],
  'Nigeria':             ['Нигерия',            'Нигерия'],
  'Cameroon':            ['Камерун',            'Камерун'],
  'Mali':                ['Мали',               'Мали'],
  'Chile':               ['Чили',               'Чили'],
  'Bolivia':             ['Боливия',            'Боливия'],
  'Peru':                ['Перу',               'Перу'],
  'Venezuela':           ['Венесуэла',          'Венесуэла'],
  'Costa Rica':          ['Коста-Рика',         'Коста-Рика'],
  'Honduras':            ['Гондурас',           'Гондурас'],
  'Guatemala':           ['Гватемала',          'Гватемала'],
  'Jamaica':             ['Ямайка',             'Ямайка'],
  'Trinidad and Tobago': ['Тринидад и Тобаго',  'Тринидад'],
  // Варианты названий от провайдеров (FlashScore / football-data)
  'Bosnia & Herzegovina': ['Босния и Герц.',     'Босния'],
  'DR Congo':            ['ДР Конго',            'Конго ДР'],
  'North Korea':         ['Северная Корея',      'КНДР'],
  'Korea DPR':           ['Северная Корея',      'КНДР'],
  'IR Iran':             ['Иран',                'Иран'],
  'Türkiye':             ['Турция',              'Турция'],
  'Faroe Islands':       ['Фарерские о-ва',      'Фареры'],
  'San Marino':          ['Сан-Марино',          'Сан-Марино'],
  'Malta':               ['Мальта',              'Мальта'],
  'Cyprus':              ['Кипр',                'Кипр'],
  'Montenegro':          ['Черногория',          'Черногория'],
  'Luxembourg':          ['Люксембург',          'Люксембург'],
  'Gibraltar':           ['Гибралтар',           'Гибралтар'],
  'Estonia':             ['Эстония',             'Эстония'],
  'Latvia':              ['Латвия',              'Латвия'],
  'Lithuania':           ['Литва',               'Литва'],
  'Bulgaria':            ['Болгария',            'Болгария'],
  'Belarus':             ['Беларусь',            'Беларусь'],
  'Moldova':             ['Молдова',             'Молдова'],
  'Armenia':             ['Армения',             'Армения'],
};

/** Canonical English display names (normalise provider/DB naming variants). */
const EN_CANON: Record<string, string> = {
  'Czechia': 'Czech Republic',
  'Bosnia-Herzegovina': 'Bosnia & Herzegovina',
  'Cape Verde Islands': 'Cape Verde',
  'Congo DR': 'DR Congo',
  'Korea Republic': 'South Korea',
  'Korea DPR': 'North Korea',
  'IR Iran': 'Iran',
  'Türkiye': 'Turkey',
};

export function getTeamName(
  name: string,
  shortName: string | null | undefined,
  locale: string,
  preferShort = false,
): string {
  if (locale !== 'ru') {
    const base = preferShort ? (shortName || name) : name;
    return EN_CANON[base] ?? EN_CANON[name] ?? base;
  }
  const ru = TEAM_NAMES_RU[name] ?? TEAM_NAMES_RU[shortName ?? ''];
  if (!ru) return preferShort ? (shortName || name) : name;
  return preferShort ? ru[1] : ru[0];
}
